pre-commit:
  run: true
  # if possible, all commands run as warnings
  fail_fast: false
  # sequence of commands to run in this pipeline
  cmds:
    - build:
        cmdName: go
        # args are ordered
        args:
          #- "-o"
          #- "binaryName"
          - "build"
          - "."
          - "errors"
    - test:
        cmdName: go
        args:
          - "test"
            #- "."
          - "-v"
    - format:
        cmdName: gofmt
        args: ["-l", "."]
        # treats output to stdout as err (such as gofmt) - returns succes when there are files to be formated
        stdoutAsErr: true
pre-push:
  run: false
  # failed command will prevent execution of next command
  fail_fast: true
  cmds:
    # commands run in specified order (build, test, format, push)
    - build:
        cmdName: go build
        args:
          - "."
    - test:
        cmdName: go test
        args:
          - "."
          - "-v"
    - format:
        cmdName: gofmt
        # as per YAML specification, can also specify order using brackets
        args: ["-l", "."]
    - push:
        cmdName: "git push"
        args:
          - "origin"
          - "main"
        # will fail if command takes longer than timeout seconds
        timeout: 5
